[package]
name = "urlp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "urlp_lib"
path = "src/lib/lib.rs"

[[bin]]
name = "urlp"
path = "src/bin.rs"

[dependencies]
nom = "7.1.0"
